Assignment: Making Your Ultimate Node.js Dockerfile

diff --git a/ultimate-node-dockerfile/Dockerfile b/ultimate-node-dockerfile/Dockerfile
--- a/ultimate-node-dockerfile/Dockerfile
+++ b/ultimate-node-dockerfile/Dockerfile
@@ -20,6 +20,16 @@ EXPOSE 80
 
 ENV NODE_ENV=production
 
+ENV TINI_VERSION v0.19.0
+ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
+RUN chmod +x /tini
+ENTRYPOINT ["/tini", "--"]
+
+RUN apt-get update && apt-get install curl -y
+
+HEALTHCHECK --interval=5m --timeout=3s \
+  CMD curl -f http://localhost/ || exit 1
+
 WORKDIR /app
 
 COPY package*.json ./
@@ -51,6 +61,8 @@ RUN npm install --only=development
 
 CMD ["nodemon", "./bin/www", "--inspect=0.0.0.0:9229"]
 
+USER node
+
 
 # Stage 3
 FROM base AS test
@@ -63,14 +75,25 @@ ENV PATH /app/node_modules/.bin:$PATH
 
 COPY --from=dev /app/node_modules /app/node_modules
 
-RUN eslint .
-
 RUN npm test
 
+# aqua microscanner, which needs a token for API access
+# note this isn't super secret, so we'll use an ARG here
+# https://github.com/aquasecurity/microscanner
+# ARG MICROSCANNER_TOKEN
+# ADD https://get.aquasec.com/microscanner /
+# RUN chmod +x /microscanner
+# RUN apk add --no-cache ca-certificates && update-ca-certificates
+# RUN /microscanner $MICROSCANNER_TOKEN --continue-on-failure
+
 CMD ["npm", "run", "int-test"]
+
+USER node
 
 
 # Stage 4
 FROM base AS prod
 
 COPY views server.js ./
+
+USER node
